apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        project: expense
        environment: dev
    spec:
      containers:
      - name: frontend
        image: arun596/frontend:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    project: expense
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
        
