apiVersion: v1
kind: Pod
metadata:
  name: env-nginx
  # one pod can contain multiple containers
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: project
      value: expense
    - name: environment
      value: dev
    - name: component
      value: backend