apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # one pod can contain multiple containers
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: dotfile-secret
          