apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-volume
spec:
  storageClassName: ebs-sc # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: e12d39b3-4b79-4409-a51d-088073d7a214
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: "ebs-dynamic-demo"
    app: nginx
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic-volume

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "ebs-dynamic-demo"
    app: nginx
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30008